server:
  port: 8080
spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/notification}
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: ${OKTA_CLIENT_ID}
            client-secret: ${OKTA_CLIENT_SECRET}
            scope: openid,profile,email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
        provider:
          okta:
            issuer-uri: https://dev-2225315.okta.com/oauth2/default
      resourceserver:
        jwt:
          issuer-uri: https://dev-2225315.okta.com/oauth2/default

  management:
    trace:
      http: enabled
    endpoints:
      web:
        exposure:
          include: "*"
